/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rami3sam.crawler;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class App {
    static String BASE_URL = "https://monzo.com";

    public static String[] getPageLinks(String pageURL)  {
        try{
        Document document = Jsoup.connect(pageURL).get();
        Elements anchorTags = document.getElementsByTag("a");

        String[] links = new String[anchorTags.size()];

        int i = 0;
        for (Element anchorTag : anchorTags){
            links[i] = anchorTag.attr("href");
            i++;
        }

        return links;
        }catch(Exception e){
            return null;
        }
    }

    public static void main(String[] args)  {
        String[] links  = getPageLinks(BASE_URL);
        for (String link : links){
            System.out.println(link);
        }
    }
}
