/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rami3sam.crawler;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import java.io.IOException;

public class App {
    static String BASE_URL = "https://monzo.com";

    public static void main(String[] args) throws IOException {
        Document document = Jsoup.connect(BASE_URL).get();
        System.out.println(document.title());
    }
}
