/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rami3sam.crawler;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import java.net.URL;
import java.io.IOException;
import java.util.ArrayList;

public class Main {
    static String BASE_URL = "https://monzo.com";

    public static ArrayList<String> getPageLinks(String pageURL)  {
        try{

            URL pageURLObject = new URL(pageURL);

            Document document = Jsoup.connect(pageURL).get();
            Elements anchorTags = document.getElementsByTag("a");

            ArrayList<String> links = new ArrayList<String>();

            int i = 0;
            for (Element anchorTag : anchorTags){
                String tempURL = anchorTag.attr("href");
                if (tempURL.startsWith("/")){
                    // in case the url is a relative url add the current pages host as a prefix
                    tempURL = pageURLObject.getAuthority() + tempURL;
                }else if(tempURL.startsWith("#")){
                    //if the url is a fragment then it's the same page and not a unique one
                    continue;
                }

                links.add(tempURL);

            }

            return links;

        }catch(IOException e){
            e.printStackTrace(System.err);
            return null;
        }
    }

    public static void main(String[] args)  {
        ArrayList<String> links  = getPageLinks(BASE_URL);
        for (String link : links){
            System.out.println(link);
        }
    }
}
